@extends('layouts.admin.app')

@section('title', 'Editar Envio')

@section('content')
    <div class="mx-auto max-w-2xl"><a href="{{ route('admin.shipments.index') }}" class="text-sm font-semibold text-[#b85d70] hover:text-[#9f4c5e]">← Voltar para envios</a><p class="mt-6 text-xs font-bold uppercase tracking-[0.18em] text-[#c96f82]">Logística</p><h1 class="mt-2 font-['Cormorant_Garamond'] text-4xl font-semibold">Editar envio</h1><p class="mt-1 text-sm text-[#746b68]">Pedido #{{ $shipment->order->id }}</p>
        <form action="{{ route('admin.shipments.update', $shipment) }}" method="POST" class="mt-7 space-y-5 rounded-2xl border border-[#eaded9] bg-white p-6 shadow-[0_8px_24px_rgba(76,50,47,0.05)]">@csrf @method('PUT')
            <div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-semibold text-[#443d3b]">Transportadora</label><input type="text" value="{{ $shipment->carrier }}" class="w-full rounded-xl border border-[#eaded9] bg-[#f8f3f1] px-4 py-3 text-sm text-[#625956]" readonly></div><div><label class="mb-2 block text-sm font-semibold text-[#443d3b]">Custo do frete</label><input type="text" value="R$ {{ number_format($shipment->shipping_cost, 2, ',', '.') }}" class="w-full rounded-xl border border-[#eaded9] bg-[#f8f3f1] px-4 py-3 text-sm text-[#625956]" readonly></div></div>
            <div><label for="tracking_code" class="mb-2 block text-sm font-semibold text-[#443d3b]">Código de rastreamento</label><input id="tracking_code" type="text" name="tracking_code" value="{{ old('tracking_code', $shipment->tracking_code) }}" class="w-full rounded-xl border border-[#ded4d0] px-4 py-3 text-sm outline-none focus:border-[#cf7184] focus:ring-4 focus:ring-[#f7dce2]" placeholder="Ex.: BR123456789"></div>
            <div><label for="status" class="mb-2 block text-sm font-semibold text-[#443d3b]">Status</label><select id="status" name="status" class="w-full rounded-xl border border-[#ded4d0] bg-white px-4 py-3 text-sm outline-none focus:border-[#cf7184] focus:ring-4 focus:ring-[#f7dce2]"><option value="pending" @selected($shipment->status == 'pending')>Pendente</option><option value="processing" @selected($shipment->status == 'processing')>Preparando</option><option value="shipped" @selected($shipment->status == 'shipped')>Enviado</option><option value="delivered" @selected($shipment->status == 'delivered')>Entregue</option><option value="cancelled" @selected($shipment->status == 'cancelled')>Cancelado</option></select></div>
            <div class="flex items-center justify-between border-t border-[#f0e5e1] pt-5"><a href="{{ route('admin.shipments.index') }}" class="text-sm font-semibold text-[#746b68] hover:text-[#443d3b]">Cancelar</a><button type="submit" class="rounded-xl bg-[#cf7184] px-4 py-3 text-sm font-bold text-white hover:bg-[#b85d70]">Atualizar envio</button></div>
        </form>
    </div>
@endsection
